### ISSUE TITLE
Installation hangs at action run

### ISSUE THREAD

**Issue by anthonygreen** [dhoer/chef-sikulix#4]
Attempting to solve issue #3 with  `export DISPLAY=:0.0`
The installer hangs at:
`* execute["/usr/bin/java" -jar "/usr/local/sikulix/sikulixsetup-1.1.0.jar" options ] action run`
because the installer is placing a dialog box on the screen of the node is attached to

**Comment by anthonygreen** [comment]
I don't have a physical monitor attached. 
Some more information that may help:
It's Xubuntu 14:04 
I'm connecting to the machine in question via ssh and then running sudo chef-client

**Comment by dhoer** [comment]
See #3
